# Training configuration for PlayListAI

# Data paths
data_dir: "data/processed"
vocab_path: "data/processed/vocab.json"
train_path: "data/processed/train.parquet"
val_path: "data/processed/val.parquet"
test_path: "data/processed/test.parquet"

# Model configuration
model:
  name: "transformer" # or "gru4rec"
  d_model: 256
  n_heads: 4
  n_layers: 2
  dropout: 0.1
  max_seq_len: 50
  ctx_dim: 2

# Training configuration
training:
  batch_size: 128
  learning_rate: 3e-4
  num_epochs: 10
  weight_decay: 1e-4
  warmup_steps: 1000
  label_smoothing: 0.1
  gradient_clip_norm: 1.0

# Ray configuration
ray:
  num_workers: 2
  use_gpu: false
  resources_per_worker:
    cpu: 2
    memory: 4000000000 # 4GB

# Evaluation
evaluation:
  metrics:
    ["recall@5", "recall@20", "ndcg@10", "coverage@100", "repetition_rate@20"]
  eval_steps: 500
  save_best: true

# Output
output:
  model_dir: "data/artifacts"
  checkpoint_name: "model.pt"
  save_embeddings: true

