apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: playlistai-ray-cluster
  namespace: default
spec:
  rayVersion: "2.35.0"
  enableInTreeAutoscaling: true
  autoscalerOptions:
    upscalingMode: Default
    idleTimeoutSeconds: 60
  headGroupSpec:
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray-ml:2.35.0-py311
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 1
                memory: 2Gi
            env:
              - name: RAY_DISABLE_IMPORT_WARNING
                value: "1"
  workerGroupSpecs:
    - groupName: worker-group
      replicas: 2
      minReplicas: 1
      maxReplicas: 4
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray-ml:2.35.0-py311
              resources:
                limits:
                  cpu: 2
                  memory: 4Gi
                requests:
                  cpu: 1
                  memory: 2Gi
              env:
                - name: RAY_DISABLE_IMPORT_WARNING
                  value: "1"

