global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "playlistai-api"
    static_configs:
      - targets: ["api:8088"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s

